spring:
  application:
    name: ToDoListBackend
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 3600000
  frontend:
    url: "http://localhost:5173"
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
  config:
    import: "optional:file:.env[.properties]"